import type { Resource } from "./crud";

const seo = [
  { column: "seo_title", key: "seoTitle", type: "text" as const },
  { column: "seo_description", key: "seoDescription", type: "text" as const },
];

export const RESOURCES: Record<string, Resource> = {
  articles: {
    table: "articles",
    label: "article",
    orderBy: "id DESC",
    slugFrom: "title",
    readPermission: "articles.read",
    writePermission: "articles.write",
    deletePermission: "articles.delete",
    fields: [
      { column: "slug", key: "slug", type: "text" },
      { column: "title", key: "title", type: "text", required: true },
      { column: "excerpt", key: "excerpt", type: "text" },
      { column: "content", key: "content", type: "text" },
      { column: "image", key: "image", type: "text" },
      { column: "category_id", key: "categoryId", type: "int" },
      { column: "author_name", key: "authorName", type: "text" },
      { column: "tags", key: "tags", type: "json" },
      { column: "status", key: "status", type: "text" },
      { column: "published_at", key: "publishedAt", type: "date" },
      ...seo,
    ],
  },

  "article-categories": {
    table: "article_categories",
    label: "catégorie d'article",
    orderBy: "position ASC, id ASC",
    slugFrom: "name",
    readPermission: "articles.read",
    writePermission: "categories.write",
    fields: [
      { column: "name", key: "name", type: "text", required: true },
      { column: "slug", key: "slug", type: "text" },
      { column: "description", key: "description", type: "text" },
      { column: "image", key: "image", type: "text" },
      { column: "position", key: "position", type: "int" },
    ],
  },

  "property-categories": {
    table: "property_categories",
    label: "catégorie de bien",
    orderBy: "position ASC, id ASC",
    slugFrom: "name",
    readPermission: "properties.read",
    writePermission: "categories.write",
    fields: [
      { column: "name", key: "name", type: "text", required: true },
      { column: "slug", key: "slug", type: "text" },
      { column: "description", key: "description", type: "text" },
      { column: "position", key: "position", type: "int" },
      { column: "published", key: "published", type: "bool" },
    ],
  },

  locations: {
    table: "locations",
    label: "localisation",
    orderBy: "position ASC, id ASC",
    slugFrom: "neighborhood",
    readPermission: "properties.read",
    writePermission: "locations.write",
    fields: [
      { column: "region", key: "region", type: "text" },
      { column: "city", key: "city", type: "text" },
      { column: "neighborhood", key: "neighborhood", type: "text", required: true },
      { column: "slug", key: "slug", type: "text" },
      { column: "description", key: "description", type: "text" },
      { column: "latitude", key: "latitude", type: "text" },
      { column: "longitude", key: "longitude", type: "text" },
      { column: "published", key: "published", type: "bool" },
      { column: "position", key: "position", type: "int" },
    ],
  },

  services: {
    table: "services",
    label: "service",
    orderBy: "position ASC, id ASC",
    slugFrom: "name",
    readPermission: "services.read",
    writePermission: "services.write",
    fields: [
      { column: "slug", key: "slug", type: "text" },
      { column: "name", key: "name", type: "text", required: true },
      { column: "name_en", key: "nameEn", type: "text" },
      { column: "short_description", key: "shortDescription", type: "text" },
      { column: "description", key: "description", type: "text" },
      { column: "description_en", key: "descriptionEn", type: "text" },
      { column: "icon", key: "icon", type: "text" },
      { column: "image", key: "image", type: "text" },
      { column: "position", key: "position", type: "int" },
      { column: "published", key: "published", type: "bool" },
    ],
  },

  testimonials: {
    table: "testimonials",
    label: "témoignage",
    orderBy: "position ASC, id DESC",
    readPermission: "gallery.read",
    writePermission: "testimonials.write",
    fields: [
      { column: "name", key: "name", type: "text", required: true },
      { column: "photo", key: "photo", type: "text" },
      { column: "content", key: "content", type: "text", required: true },
      { column: "location", key: "location", type: "text" },
      { column: "rating", key: "rating", type: "int" },
      { column: "is_demo", key: "isDemo", type: "bool" },
      { column: "published", key: "published", type: "bool" },
      { column: "position", key: "position", type: "int" },
    ],
  },

  team: {
    table: "team_members",
    label: "membre de l'équipe",
    orderBy: "position ASC, id ASC",
    readPermission: "services.read",
    writePermission: "team.write",
    fields: [
      { column: "name", key: "name", type: "text", required: true },
      { column: "role", key: "role", type: "text" },
      { column: "photo", key: "photo", type: "text" },
      { column: "bio", key: "bio", type: "text" },
      { column: "phone", key: "phone", type: "text" },
      { column: "email", key: "email", type: "text" },
      { column: "position", key: "position", type: "int" },
      { column: "published", key: "published", type: "bool" },
    ],
  },

  gallery: {
    table: "gallery_items",
    label: "image de galerie",
    orderBy: "position ASC, id DESC",
    readPermission: "gallery.read",
    writePermission: "gallery.write",
    fields: [
      { column: "image", key: "image", type: "text", required: true },
      { column: "title", key: "title", type: "text" },
      { column: "caption", key: "caption", type: "text" },
      { column: "alt", key: "alt", type: "text" },
      { column: "category", key: "category", type: "text" },
      { column: "position", key: "position", type: "int" },
      { column: "published", key: "published", type: "bool" },
    ],
  },

  "homepage-sections": {
    table: "homepage_sections",
    label: "section d'accueil",
    orderBy: "position ASC, id ASC",
    readPermission: "properties.read",
    writePermission: "homepage.write",
    fields: [
      { column: "block_type", key: "blockType", type: "text", required: true },
      { column: "title", key: "title", type: "text" },
      { column: "subtitle", key: "subtitle", type: "text" },
      { column: "config", key: "config", type: "json" },
      { column: "position", key: "position", type: "int" },
      { column: "enabled", key: "enabled", type: "bool" },
    ],
  },

  customers: {
    table: "customers",
    label: "client",
    orderBy: "id DESC",
    readPermission: "customers.read",
    writePermission: "customers.write",
    fields: [
      { column: "name", key: "name", type: "text", required: true },
      { column: "phone", key: "phone", type: "text" },
      { column: "email", key: "email", type: "text" },
      { column: "notes", key: "notes", type: "text" },
      { column: "agent_id", key: "agentId", type: "int" },
    ],
  },

  appointments: {
    table: "appointments",
    label: "rendez-vous",
    orderBy: "scheduled_at DESC",
    readPermission: "appointments.read",
    writePermission: "appointments.write",
    fields: [
      { column: "customer_name", key: "customerName", type: "text", required: true },
      { column: "customer_phone", key: "customerPhone", type: "text" },
      { column: "property_id", key: "propertyId", type: "int" },
      { column: "property_title", key: "propertyTitle", type: "text" },
      { column: "scheduled_at", key: "scheduledAt", type: "date", required: true },
      { column: "location", key: "location", type: "text" },
      { column: "agent_id", key: "agentId", type: "int" },
      { column: "notes", key: "notes", type: "text" },
      { column: "status", key: "status", type: "text" },
    ],
  },

  faqs: {
    table: "faqs",
    label: "FAQ",
    orderBy: "position ASC, id ASC",
    readPermission: "ai.read",
    writePermission: "ai.write",
    fields: [
      { column: "question", key: "question", type: "text", required: true },
      { column: "answer", key: "answer", type: "text", required: true },
      { column: "category", key: "category", type: "text" },
      { column: "position", key: "position", type: "int" },
      { column: "published", key: "published", type: "bool" },
    ],
  },

  "ai-knowledge": {
    table: "ai_knowledge",
    label: "connaissance IA",
    orderBy: "position ASC, id ASC",
    readPermission: "ai.read",
    writePermission: "ai.write",
    fields: [
      { column: "title", key: "title", type: "text", required: true },
      { column: "content", key: "content", type: "text", required: true },
      { column: "keywords", key: "keywords", type: "json" },
      { column: "category", key: "category", type: "text" },
      { column: "published", key: "published", type: "bool" },
      { column: "position", key: "position", type: "int" },
    ],
  },
};
