import type { NewPropertyRow } from "./schema";

const px = (id: number, w = 1400, h = 900) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

export const seedProperties: NewPropertyRow[] = [
  {
    slug: "maison-villa-a-vendre-douala-yassa-cite-chirac",
    title: "Maison / Villa neuve — Yassa, Cité Chirac",
    titleEn: "Brand-new house / villa — Yassa, Cité Chirac",
    description:
      "Villa familiale neuve implantée dans la Cité Chirac à Yassa, un quartier résidentiel en pleine structuration au sud de Douala. La maison s'organise autour d'un salon lumineux, de quatre chambres, de trois salles de bains et d'une cuisine indépendante, prolongés par un balcon. L'ensemble est carrelé, climatisé et livré en état neuf.\n\nLa parcelle d'environ 500 m² accueille une surface habitable d'environ 410 m², un parking privatif et une barrière de clôture. L'accès se fait en voiture, à environ 100 mètres de la route principale, ce qui facilite les déplacements quotidiens vers le centre de Douala et l'aéroport.",
    descriptionEn:
      "Brand-new family villa located in Cité Chirac, Yassa, a fast-developing residential area in the south of Douala. The layout offers a bright living room, four bedrooms, three bathrooms and a separate kitchen, extended by a balcony. The whole property is tiled, air-conditioned and delivered in new condition.\n\nThe plot of approximately 500 sqm carries around 410 sqm of living space, private parking and a perimeter gate. Car access is direct, about 100 metres from the main road, making daily trips to central Douala and the airport straightforward.",
    city: "Douala",
    neighborhood: "Yassa",
    address: "Yassa, Cité Chirac, Douala",
    propertyType: "Villa",
    transactionType: "vente",
    price: 250000000,
    pricePeriod: "",
    bedrooms: 4,
    bathrooms: 3,
    livingRooms: 1,
    livingArea: 410,
    landArea: 500,
    parkingSpaces: 1,
    condition: "Neuf",
    amenities: [
      "Climatisation",
      "Balcon",
      "Sol carrelé",
      "Cuisine équipée d'origine",
      "Parking",
      "Barrière",
      "Accessible en voiture",
      "À environ 100 m de la route principale",
    ],
    amenitiesEn: [
      "Air conditioning",
      "Balcony",
      "Tiled floors",
      "Fitted kitchen",
      "Parking",
      "Gated entrance",
      "Car access",
      "About 100 m from the main road",
    ],
    images: [px(8092394), px(13600823), px(7546281), px(6508347)],
    featured: true,
    source: "Koutchoumi",
    sourceUrl:
      "https://koutchoumi.com/fr/123532/maison-villa-a-vendre-douala-yassa-cite-chirac-1-salon-s-4-chambre-s-3-salle-s-de-bains-250-000-009-fcfa",
    sourceReference: "koutchoumi-123532",
    seoTitle:
      "Villa 4 chambres à vendre à Yassa Cité Chirac, Douala — 250 000 000 FCFA",
    seoDescription:
      "Villa neuve de 4 chambres et 3 salles de bains à Yassa Cité Chirac, Douala. 410 m² habitables sur 500 m² de terrain, parking, climatisation. 250 000 000 FCFA.",
  },
  {
    slug: "immeuble-r5-a-vendre-douala-akwa",
    title: "Immeuble R+5 — Akwa I, Douala",
    titleEn: "R+5 building — Akwa I, Douala",
    description:
      "Immeuble R+5 d'environ 1 000 m² situé à Akwa I, au cœur du quartier d'affaires de Douala. Le bâtiment est équipé d'un ascenseur, d'un groupe électrogène, de la fibre optique, d'un système d'accès digital et d'un totem signalétique en façade. Le gardiennage est assuré 24h/24.\n\nLe bâtiment dispose de l'eau, d'un compteur prépayé, de plusieurs bureaux ainsi que de bureaux supplémentaires à l'arrière et d'un grand parking. Selon l'annonce d'origine, il comprend 50 salons, 100 chambres et 100 salles de bains. Le bien convient à un siège social, un business center, des plateaux de bureaux, une administration ou un investissement locatif. Une mise en location est également envisageable autour de 15 000 FCFA/m².",
    descriptionEn:
      "R+5 building of approximately 1,000 sqm located in Akwa I, at the heart of Douala's business district. It is equipped with a lift, a generator, fibre optic connectivity, a digital access system and a signage totem on the facade. Security guarding is provided 24/7.\n\nThe building has running water, a prepaid meter, several offices plus additional offices at the rear, and a large car park. According to the original listing it comprises 50 living rooms, 100 bedrooms and 100 bathrooms. It suits a headquarters, a business center, office floors, an administration or an investment. A rental arrangement of around 15,000 FCFA/sqm is also possible.",
    city: "Douala",
    neighborhood: "Akwa",
    address: "Akwa I, Akwa, Douala",
    propertyType: "Immeuble",
    transactionType: "vente",
    price: 1200000000,
    bedrooms: 100,
    bathrooms: 100,
    livingRooms: 50,
    livingArea: 1000,
    amenities: [
      "Ascenseur",
      "Groupe électrogène",
      "Fibre optique",
      "Gardiennage 24h/24",
      "Système d'accès digital",
      "Totem signalétique",
      "Eau",
      "Compteur prépayé",
      "Plusieurs bureaux",
      "Bureaux supplémentaires à l'arrière",
      "Grand parking",
    ],
    amenitiesEn: [
      "Lift",
      "Backup generator",
      "Fibre optic",
      "24/7 security",
      "Digital access system",
      "Signage totem",
      "Running water",
      "Prepaid meter",
      "Several offices",
      "Additional offices at the rear",
      "Large car park",
    ],
    images: [px(4448829), px(33719851), px(18468708), px(37073624)],
    featured: true,
    source: "Koutchoumi",
    sourceUrl:
      "https://koutchoumi.com/fr/123491/maison-concession-a-vendre-douala-akwa-i-akwa-50-salon-s-100-chambre-s-100-salle-s-de-bains-1-200-000-000-fcfa",
    sourceReference: "koutchoumi-123491",
    seoTitle: "Immeuble R+5 à vendre à Akwa, Douala — 1 200 000 000 FCFA",
    seoDescription:
      "Immeuble R+5 de 1 000 m² à Akwa I, Douala : ascenseur, groupe électrogène, fibre optique, gardiennage 24h/24, grand parking. À vendre à 1 200 000 000 FCFA.",
  },
  {
    slug: "villa-a-vendre-douala-bonapriso-hotel-de-l-air",
    title: "Villa — Bonapriso, Hôtel de l'Air",
    titleEn: "Villa — Bonapriso, Hôtel de l'Air",
    description:
      "Villa située à Bonapriso, secteur Hôtel de l'Air, l'une des adresses résidentielles les plus recherchées de Douala. Elle propose un salon, quatre chambres, trois salles de bains et une cuisine, avec balcon, sol carrelé et état neuf.\n\nLa propriété s'étend sur environ 659 m², entièrement clôturée par une barrière, avec espace vert, boucarreau et un parking pouvant accueillir environ trois véhicules. Un terrain restant à l'arrière débouche sur une autre rue : il offre la possibilité d'y construire un immeuble de rapport. L'accès se fait en voiture et le bien est desservi en eau.",
    descriptionEn:
      "Villa located in Bonapriso, Hôtel de l'Air area, one of the most sought-after residential addresses in Douala. It offers a living room, four bedrooms, three bathrooms and a kitchen, with a balcony, tiled floors and new condition.\n\nThe property covers approximately 659 sqm, fully enclosed by a gate, with a green area, paved surfacing and parking for around three vehicles. Remaining land at the rear opens onto another street and could accommodate a rental building. Car access and a water supply are available.",
    city: "Douala",
    neighborhood: "Bonapriso",
    address: "Bonapriso, Hôtel de l'Air, Douala",
    propertyType: "Villa",
    transactionType: "vente",
    price: 500000000,
    bedrooms: 4,
    bathrooms: 3,
    livingRooms: 1,
    livingArea: 659,
    landArea: 659,
    parkingSpaces: 3,
    condition: "Neuf",
    amenities: [
      "Balcon",
      "Sol carrelé",
      "Espace vert",
      "Boucarreau",
      "Parking pour environ 3 véhicules",
      "Barrière",
      "Accessible en voiture",
      "Eau",
      "Terrain restant à l'arrière ouvrant sur une autre rue",
    ],
    amenitiesEn: [
      "Balcony",
      "Tiled floors",
      "Green area",
      "Paved surfacing",
      "Parking for about 3 vehicles",
      "Gated entrance",
      "Car access",
      "Water supply",
      "Remaining rear land opening onto another street",
    ],
    images: [px(8134847), px(24807128), px(8134750), px(8134762)],
    featured: true,
    source: "Koutchoumi",
    sourceUrl:
      "https://koutchoumi.com/fr/123074/maison-villa-a-vendre-douala-bonapriso-hotel-de-l-air-1-salon-s-4-chambre-s-3-salle-s-de-bains-500-000-000-fcfa",
    sourceReference: "koutchoumi-123074",
    seoTitle: "Villa 4 chambres à vendre à Bonapriso, Douala — 500 000 000 FCFA",
    seoDescription:
      "Villa de 4 chambres et 3 salles de bains à Bonapriso, Hôtel de l'Air, Douala. Environ 659 m², espace vert, parking 3 véhicules. À vendre à 500 000 000 FCFA.",
  },
  {
    slug: "entrepot-commercial-a-louer-douala-bonaberi-ndobo",
    title: "Entrepôt commercial 2 000 m² — Bonabéri, Ndobo",
    titleEn: "2,000 sqm commercial warehouse — Bonabéri, Ndobo",
    description:
      "Entrepôt commercial d'environ 2 000 m², entièrement couvert, situé à Ndobo, Bonabéri, sur l'axe logistique le plus actif de Douala. Le volume dégagé et la circulation intérieure permettent d'organiser librement le stockage, la préparation de commandes et la distribution.\n\nLe site dispose d'environ 47 places de stationnement, ce qui facilite la rotation des véhicules de livraison et l'accueil des équipes. Il convient aux opérateurs logistiques, aux distributeurs, aux importateurs et aux entreprises commerciales recherchant une surface de stockage immédiatement exploitable.",
    descriptionEn:
      "Commercial warehouse of approximately 2,000 sqm, entirely covered, located in Ndobo, Bonabéri, on Douala's busiest logistics corridor. The clear volume and internal circulation allow storage, order preparation and distribution to be organised freely.\n\nThe site offers around 47 parking spaces, which eases delivery vehicle rotation and team access. It suits logistics operators, distributors, importers and commercial companies looking for immediately usable storage space.",
    city: "Douala",
    neighborhood: "Bonabéri",
    address: "Ndobo, Bonabéri, Douala",
    propertyType: "Entrepôt",
    transactionType: "location",
    price: 7000000,
    pricePeriod: "mois",
    livingArea: 2000,
    parkingSpaces: 47,
    amenities: [
      "Entièrement couvert",
      "Environ 47 places de parking",
      "Adapté au stockage",
      "Adapté à la distribution",
      "Accès et circulation aisés",
    ],
    amenitiesEn: [
      "Entirely covered",
      "About 47 parking spaces",
      "Suitable for storage",
      "Suitable for distribution",
      "Easy access and circulation",
    ],
    images: [px(36217325), px(236698), px(4170172), px(34207364)],
    featured: true,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-bonaberi-entrepot-commercial-2000-m-bonaberi-ndobo-b8a905a4",
    sourceReference: "selogercm-b8a905a4",
    seoTitle:
      "Entrepôt 2 000 m² à louer à Bonabéri Ndobo, Douala — 7 000 000 FCFA/mois",
    seoDescription:
      "Entrepôt commercial couvert de 2 000 m² à Ndobo, Bonabéri, Douala. Environ 47 places de parking, idéal logistique et distribution. 7 000 000 FCFA/mois.",
  },
  {
    slug: "appartement-3-chambres-a-louer-douala-akwa-orange",
    title: "Appartement 3 chambres avec vue piscine — Akwa",
    titleEn: "3-bedroom apartment with pool view — Akwa",
    description:
      "Appartement de trois chambres et trois salles de bains situé au premier étage d'une résidence sécurisée d'Akwa, à quelques minutes de la Direction Générale d'Orange. Le séjour ouvre sur un balcon offrant une vue dégagée sur la piscine de la résidence.\n\nLe logement est climatisé et bénéficie d'une alimentation en eau courante par forage, d'un groupe électrogène, d'un gardien, de la vidéosurveillance et d'un parking. Son emplacement central permet de rejoindre rapidement les principaux sièges d'entreprises, banques et commerces d'Akwa.",
    descriptionEn:
      "Three-bedroom, three-bathroom apartment on the first floor of a secured residence in Akwa, minutes from the Orange General Directorate. The living room opens onto a balcony with an open view over the residence pool.\n\nThe apartment is air-conditioned and benefits from borehole running water, a backup generator, a caretaker, video surveillance and parking. Its central position gives quick access to Akwa's main corporate offices, banks and shops.",
    city: "Douala",
    neighborhood: "Akwa",
    address: "Akwa, près de la Direction Générale Orange, Douala",
    propertyType: "Appartement",
    transactionType: "location",
    price: 900000,
    pricePeriod: "mois",
    bedrooms: 3,
    bathrooms: 3,
    floor: "1er étage",
    amenities: [
      "Climatisation",
      "Balcon",
      "Vue sur piscine",
      "Parking",
      "Eau courante via forage",
      "Gardien",
      "Vidéosurveillance",
      "Groupe électrogène",
      "Emplacement central",
    ],
    amenitiesEn: [
      "Air conditioning",
      "Balcony",
      "Pool view",
      "Parking",
      "Borehole running water",
      "Caretaker",
      "Video surveillance",
      "Backup generator",
      "Central location",
    ],
    images: [px(12148587), px(14024795), px(6434592), px(7045767)],
    featured: true,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-akwa-akwa-appartement-3-chambres-pres-orange-vue-piscine-e456e360",
    sourceReference: "selogercm-e456e360",
    seoTitle:
      "Appartement 3 chambres à louer à Akwa, Douala — 900 000 FCFA/mois",
    seoDescription:
      "Appartement meublé de 3 chambres et 3 salles de bains à Akwa, Douala, vue piscine, climatisation, gardien, groupe électrogène. 900 000 FCFA/mois.",
  },
  {
    slug: "appartement-2-chambres-a-louer-douala-akwa-soudanaise",
    title: "Appartement 2 chambres — Akwa, près Soudanaise",
    titleEn: "2-bedroom apartment — Akwa, near Soudanaise",
    description:
      "Appartement de deux chambres situé au 5e étage d'un immeuble d'Akwa, à proximité immédiate de la Soudanaise. Une adresse centrale pour un cadre, un couple ou une petite famille souhaitant vivre au plus près des commerces, banques et bureaux du centre-ville de Douala.\n\nLe loyer mensuel est de 600 000 FCFA. Notre équipe organise la visite et vous accompagne jusqu'à la signature du bail.",
    descriptionEn:
      "Two-bedroom apartment on the 5th floor of a building in Akwa, right next to Soudanaise. A central address for a professional, a couple or a small family who wants to live close to the shops, banks and offices of downtown Douala.\n\nThe monthly rent is 600,000 FCFA. Our team arranges the viewing and supports you through to the signature of the lease.",
    city: "Douala",
    neighborhood: "Akwa",
    address: "Akwa, près Soudanaise, Douala",
    propertyType: "Appartement",
    transactionType: "location",
    price: 600000,
    pricePeriod: "mois",
    bedrooms: 2,
    floor: "5e étage",
    amenities: ["Proche de la Soudanaise", "Emplacement central"],
    amenitiesEn: ["Close to Soudanaise", "Central location"],
    images: [px(9877285), px(6585619), px(6636302), px(26346376)],
    featured: false,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-akwa-akwa-pres-soudanaise-appartement-2-chambres-5e-etage-600-000-fcfa-2dc660d3",
    sourceReference: "selogercm-2dc660d3",
    seoTitle:
      "Appartement 2 chambres à louer à Akwa, Douala — 600 000 FCFA/mois",
    seoDescription:
      "Appartement de 2 chambres au 5e étage à Akwa, près Soudanaise, Douala. Location à 600 000 FCFA par mois avec La Maison Bibi.",
  },
  {
    slug: "duplex-6-chambres-a-louer-douala-bonanjo",
    title: "Duplex 6 chambres — Bonanjo, Centre administratif",
    titleEn: "6-bedroom duplex — Bonanjo, administrative centre",
    description:
      "Duplex de six chambres implanté à Bonanjo, dans le centre administratif de Douala, à proximité des institutions, des ambassades et des sièges d'entreprises. Le volume sur deux niveaux convient aussi bien à une grande famille qu'à une résidence de direction ou à des bureaux de représentation.\n\nLe loyer est d'environ 3 000 000 FCFA. La Maison Bibi organise les visites et vous accompagne dans la constitution du dossier de location.",
    descriptionEn:
      "Six-bedroom duplex located in Bonanjo, Douala's administrative centre, close to institutions, embassies and corporate headquarters. The two-level layout suits a large family as well as an executive residence or representative offices.\n\nThe rent is approximately 3,000,000 FCFA. La Maison Bibi arranges viewings and assists you with the rental application.",
    city: "Douala",
    neighborhood: "Bonanjo",
    address: "Bonanjo, Centre administratif, Douala",
    propertyType: "Duplex",
    transactionType: "location",
    price: 3000000,
    pricePeriod: "mois",
    bedrooms: 6,
    amenities: ["Centre administratif", "Duplex sur deux niveaux"],
    amenitiesEn: ["Administrative centre", "Two-level duplex"],
    images: [px(5997959), px(7031410), px(7061408), px(7031592)],
    featured: false,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-bonanjo-duplex-6-chambres-bonanjo-centre-administratif-3m-fcfa-0484214c",
    sourceReference: "selogercm-0484214c",
    seoTitle: "Duplex 6 chambres à louer à Bonanjo, Douala — 3 000 000 FCFA",
    seoDescription:
      "Duplex de 6 chambres à Bonanjo, centre administratif de Douala. Location à environ 3 000 000 FCFA avec La Maison Bibi.",
  },
  {
    slug: "appartement-3-chambres-a-louer-douala-bonapriso-hydrocarbures",
    title: "Appartement 3 chambres — Bonapriso, Hydrocarbures",
    titleEn: "3-bedroom apartment — Bonapriso, Hydrocarbures",
    description:
      "Appartement de trois chambres, trois salles de bains et un salon situé au quartier Hydrocarbures, à Bonapriso. Le secteur est apprécié pour son calme résidentiel, ses commerces de proximité et sa proximité immédiate du centre des affaires de Douala.\n\nLe loyer mensuel est de 1 000 000 FCFA. Nos conseillers vous présentent le bien et vous accompagnent tout au long de la location.",
    descriptionEn:
      "Three-bedroom, three-bathroom apartment with a living room located in the Hydrocarbures area of Bonapriso. The district is valued for its residential calm, its local shops and its immediate proximity to Douala's business centre.\n\nThe monthly rent is 1,000,000 FCFA. Our advisors present the property and support you throughout the rental process.",
    city: "Douala",
    neighborhood: "Bonapriso",
    address: "Hydrocarbures, Bonapriso, Douala",
    propertyType: "Appartement",
    transactionType: "location",
    price: 1000000,
    pricePeriod: "mois",
    bedrooms: 3,
    bathrooms: 3,
    livingRooms: 1,
    amenities: ["Quartier résidentiel de Bonapriso"],
    amenitiesEn: ["Residential Bonapriso district"],
    images: [px(7031712), px(8089081), px(6920631), px(7061333)],
    featured: false,
    source: "Koutchoumi",
    sourceUrl:
      "https://koutchoumi.com/en/123467/apartment-to-rent-douala-bonapriso-hydrocarbures-1-living-room-s-3-bedroom-s-3-bathroom-s-1-000-000-fcfa-month",
    sourceReference: "koutchoumi-123467",
    seoTitle:
      "Appartement 3 chambres à louer à Bonapriso, Douala — 1 000 000 FCFA/mois",
    seoDescription:
      "Appartement de 3 chambres et 3 salles de bains au quartier Hydrocarbures, Bonapriso, Douala. Location à 1 000 000 FCFA par mois.",
  },
  {
    slug: "maison-duplex-a-vendre-douala-youpwe-marina",
    title: "Maison duplex 4 chambres — Youpwe, Marina",
    titleEn: "4-bedroom duplex house — Youpwe, Marina",
    description:
      "Maison duplex située à Youpwe, secteur Marina, à proximité de Bonapriso. Elle se compose d'un salon, de quatre chambres, de quatre salles de bains et d'une cuisine, complétés par un balcon. L'ensemble est carrelé et se présente en bon état.\n\nLa parcelle mesure environ 300 m², clôturée par une barrière et dotée d'un parking. Le bien se trouve à environ 100 mètres de la route principale ; l'annonce d'origine précise que l'accès en voiture est limité. Les documents sont disponibles selon le vendeur. Une opportunité intéressante pour une famille ou un investisseur souhaitant se positionner sur ce secteur en développement de Douala.",
    descriptionEn:
      "Duplex house located in Youpwe, Marina area, close to Bonapriso. It comprises a living room, four bedrooms, four bathrooms and a kitchen, plus a balcony. The property is tiled throughout and is in good condition.\n\nThe plot measures approximately 300 sqm, enclosed by a gate and fitted with parking. The property sits about 100 metres from the main road; the original listing states that car access is limited. Documents are available according to the seller. An interesting opportunity for a family or an investor looking at this developing part of Douala.",
    city: "Douala",
    neighborhood: "Youpwe",
    address: "Youpwe, Marina, Douala",
    propertyType: "Duplex",
    transactionType: "vente",
    price: 170000000,
    bedrooms: 4,
    bathrooms: 4,
    livingRooms: 1,
    landArea: 300,
    condition: "Bon état",
    amenities: [
      "Balcon",
      "Sol carrelé",
      "Parking",
      "Barrière",
      "À environ 100 m de la route principale",
      "Proche de Bonapriso",
      "Documents disponibles",
      "Accès en voiture limité",
    ],
    amenitiesEn: [
      "Balcony",
      "Tiled floors",
      "Parking",
      "Gated entrance",
      "About 100 m from the main road",
      "Close to Bonapriso",
      "Documents available",
      "Limited car access",
    ],
    images: [px(36202205), px(10670391), px(7031591), px(6438745)],
    featured: true,
    source: "Koutchoumi",
    sourceUrl:
      "https://koutchoumi.com/fr/123548/maison-duplex-a-vendre-douala-youpwe-marina-1-salon-s-4-chambre-s-4-salle-s-de-bains-170-000-000-fcfa",
    sourceReference: "koutchoumi-123548",
    seoTitle:
      "Maison duplex 4 chambres à vendre à Youpwe Marina, Douala — 170 000 000 FCFA",
    seoDescription:
      "Duplex de 4 chambres et 4 salles de bains à Youpwe Marina, Douala. Terrain d'environ 300 m², parking, barrière, proche de Bonapriso. À vendre à 170 000 000 FCFA.",
  },
  {
    slug: "appartement-3-chambres-a-louer-douala-bonanjo",
    title: "Appartement 3 chambres de standing — Bonanjo",
    titleEn: "3-bedroom high-standing apartment — Bonanjo",
    description:
      "Appartement moderne et élégant à Bonanjo, l'un des quartiers les plus recherchés de Douala 1er. Le logement s'articule autour d'un grand séjour lumineux, de trois chambres, de trois salles d'eau et d'un WC visiteurs, servis par une cuisine fonctionnelle.\n\nLa surface annoncée est d'environ 321 m², un volume rare pour un appartement en centre administratif. L'adresse convient particulièrement aux cadres, aux expatriés et aux familles qui souhaitent résider à quelques minutes des institutions, des banques et des sièges d'entreprises.",
    descriptionEn:
      "Modern and elegant apartment in Bonanjo, one of the most sought-after districts of Douala 1er. The layout is organised around a large, bright living room, three bedrooms, three shower rooms and a guest toilet, served by a functional kitchen.\n\nThe advertised surface is approximately 321 sqm, a rare volume for an apartment in the administrative centre. The address particularly suits executives, expatriates and families wishing to live minutes from institutions, banks and corporate headquarters.",
    city: "Douala",
    neighborhood: "Bonanjo",
    address: "Bonanjo, Douala 1er",
    propertyType: "Appartement",
    transactionType: "location",
    price: 800000,
    pricePeriod: "mois",
    bedrooms: 3,
    bathrooms: 3,
    livingRooms: 1,
    livingArea: 321,
    amenities: [
      "Grand séjour lumineux",
      "Cuisine fonctionnelle",
      "3 salles d'eau",
      "WC visiteurs",
      "Quartier recherché de Douala",
    ],
    amenitiesEn: [
      "Large bright living room",
      "Functional kitchen",
      "3 shower rooms",
      "Guest toilet",
      "Sought-after Douala district",
    ],
    images: [px(7061335), px(6434612), px(7167061), px(30386993)],
    featured: true,
    source: "Keur Immo",
    sourceUrl:
      "https://keur-immo.com/cameroun/annonce-immobiliere-cameroun/douala-bonanjo-magnifique-appartement-bon-standing-a-louer/",
    sourceReference: "keurimmo-bonanjo-standing",
    seoTitle:
      "Appartement 3 chambres à louer à Bonanjo, Douala — 800 000 FCFA/mois",
    seoDescription:
      "Appartement de standing de 3 chambres et 3 salles d'eau à Bonanjo, Douala 1er. Environ 321 m², grand séjour lumineux, cuisine fonctionnelle. 800 000 FCFA/mois.",
  },
  {
    slug: "grand-espace-bureaux-a-louer-douala-bali",
    title: "Grand espace bureaux sur deux niveaux — Bali",
    titleEn: "Large two-level office space — Bali",
    description:
      "Vaste plateau de bureaux réparti sur deux niveaux à Bali, implanté le long de la route principale. Chaque niveau développe environ 150 m² et dispose de trois toilettes, auxquelles s'ajoute une kitchenette pour le confort des équipes.\n\nLe site bénéficie d'un parking sécurisé et d'un gardiennage 24h/24. Une vidéo de présentation est disponible auprès de notre équipe. Le loyer est d'environ 800 000 FCFA par mois et reste négociable. Une localisation de premier plan pour une agence, un cabinet, une direction commerciale ou une représentation.",
    descriptionEn:
      "Large office floor plate spread over two levels in Bali, positioned along the main road. Each level offers approximately 150 sqm and includes three toilets, complemented by a kitchenette for staff comfort.\n\nThe site benefits from secure parking and 24/7 security. A presentation video is available from our team. The rent is approximately 800,000 FCFA per month and remains negotiable. A prime location for an agency, a practice, a sales division or a representative office.",
    city: "Douala",
    neighborhood: "Bali",
    address: "Bali, le long de la route principale, Douala",
    propertyType: "Bureau",
    transactionType: "location",
    price: 800000,
    pricePeriod: "mois",
    livingArea: 300,
    amenities: [
      "Deux niveaux",
      "Environ 150 m² par niveau",
      "3 toilettes par niveau",
      "Kitchenette",
      "Parking sécurisé",
      "Gardiennage 24h/24",
      "Le long de la route principale",
      "Loyer négociable",
    ],
    amenitiesEn: [
      "Two levels",
      "About 150 sqm per level",
      "3 toilets per level",
      "Kitchenette",
      "Secure parking",
      "24/7 security",
      "Along the main road",
      "Negotiable rent",
    ],
    images: [px(6794925), px(7534175), px(6899393), px(8353778)],
    featured: true,
    source: "Keur Immo",
    sourceUrl:
      "https://keur-immo.com/cameroun/annonce-immobiliere-cameroun/douala-bali-tres-grand-bureaux-a-louer/",
    sourceReference: "keurimmo-bali-bureaux",
    seoTitle: "Bureaux à louer à Bali, Douala — 800 000 FCFA/mois",
    seoDescription:
      "Grand espace bureaux sur deux niveaux à Bali, Douala. Environ 150 m² par niveau, kitchenette, parking sécurisé, gardiennage 24h/24. 800 000 FCFA/mois négociables.",
  },
  {
    slug: "duplex-3-chambres-a-louer-douala-bonapriso-njo-njo",
    title: "Duplex 3 chambres avec jardin et piscine — Bonapriso",
    titleEn: "3-bedroom duplex with garden and pool — Bonapriso",
    description:
      "Duplex résidentiel de standing situé rue Njo Njo, à Bonapriso, dans un environnement calme et verdoyant. Il propose trois chambres et trois salles de bains réparties sur deux niveaux, avec un jardin privatif et une piscine.\n\nLe bien dispose d'un parking et de l'eau courante. Il est proposé non meublé, ce qui laisse toute liberté d'aménagement. Une adresse de référence pour une famille, un cadre expatrié ou une résidence de fonction à Douala.",
    descriptionEn:
      "High-standing residential duplex located on rue Njo Njo in Bonapriso, in a quiet and leafy environment. It offers three bedrooms and three bathrooms across two levels, with a private garden and a swimming pool.\n\nThe property includes parking and running water. It is offered unfurnished, leaving full freedom of layout. A benchmark address for a family, an expatriate executive or a company residence in Douala.",
    city: "Douala",
    neighborhood: "Bonapriso",
    address: "Rue Njo Njo, Bonapriso, Douala",
    propertyType: "Duplex",
    transactionType: "location",
    price: 1700000,
    pricePeriod: "mois",
    bedrooms: 3,
    bathrooms: 3,
    amenities: [
      "Jardin",
      "Piscine",
      "Parking",
      "Eau courante",
      "Non meublé",
      "Environnement résidentiel",
    ],
    amenitiesEn: [
      "Garden",
      "Swimming pool",
      "Parking",
      "Running water",
      "Unfurnished",
      "Residential environment",
    ],
    images: [px(36418268), px(14024947), px(30165029), px(7031573)],
    featured: true,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-bonapriso-duplex-3-chambres-avec-jardin-et-piscine-rue-njo-njo-3f7346f3",
    sourceReference: "selogercm-3f7346f3",
    seoTitle:
      "Duplex 3 chambres avec piscine à louer à Bonapriso, Douala — 1 700 000 FCFA/mois",
    seoDescription:
      "Duplex de 3 chambres avec jardin et piscine rue Njo Njo, Bonapriso, Douala. Parking, eau courante, non meublé. Location à 1 700 000 FCFA par mois.",
  },
  {
    slug: "shop-190-m2-a-louer-douala-logpom-rhone-poulenc",
    title: "Shop 190 m² — Logpom, Carrefour Rhône-Poulenc",
    titleEn: "190 sqm shop — Logpom, Carrefour Rhône-Poulenc",
    description:
      "Local commercial de 190 m² situé au carrefour Rhône-Poulenc, à Logpom. En bordure de route, il bénéficie d'une excellente visibilité sur un axe très fréquenté, un atout déterminant pour une enseigne, une agence ou un showroom.\n\nL'espace s'organise autour d'une grande zone avant, d'une grande zone arrière et d'une mezzanine, offrant une configuration commerciale flexible. Un parking complète l'ensemble. Le loyer est de 1 250 000 FCFA par mois.",
    descriptionEn:
      "190 sqm commercial unit located at the Rhône-Poulenc junction in Logpom. Set on the roadside, it enjoys excellent visibility on a busy route, a decisive asset for a retail brand, an agency or a showroom.\n\nThe space is organised around a large front area, a large rear area and a mezzanine, offering a flexible commercial configuration. Parking completes the offer. The rent is 1,250,000 FCFA per month.",
    city: "Douala",
    neighborhood: "Logpom",
    address: "Carrefour Rhône-Poulenc, Logpom, Douala",
    propertyType: "Local commercial",
    transactionType: "location",
    price: 1250000,
    pricePeriod: "mois",
    livingArea: 190,
    amenities: [
      "Excellente visibilité",
      "Bordure de route",
      "Mezzanine",
      "Grande zone avant",
      "Grande zone arrière",
      "Parking",
      "Configuration commerciale flexible",
    ],
    amenitiesEn: [
      "Excellent visibility",
      "Roadside location",
      "Mezzanine",
      "Large front area",
      "Large rear area",
      "Parking",
      "Flexible commercial layout",
    ],
    images: [px(13068373), px(36080798), px(30929605), px(13068378)],
    featured: false,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-logpom-shop-190-m-logpom-carrefour-rhone-poulenc-1485f85b",
    sourceReference: "selogercm-1485f85b",
    seoTitle:
      "Local commercial 190 m² à louer à Logpom, Douala — 1 250 000 FCFA/mois",
    seoDescription:
      "Shop de 190 m² au carrefour Rhône-Poulenc, Logpom, Douala. Bordure de route, mezzanine, parking, excellente visibilité. Location à 1 250 000 FCFA par mois.",
  },
  {
    slug: "entrepot-2000-m2-a-louer-douala-zone-portuaire-bonanjo",
    title: "Entrepôt 2 000 m² — Zone portuaire, Bonanjo",
    titleEn: "2,000 sqm warehouse — Port zone, Bonanjo",
    description:
      "Entrepôt de 2 000 m² implanté en zone portuaire-Bonanjo, à proximité immédiate de Bonanjo Gate 1, du Marché des Fleurs et de Bonapriso. L'emplacement offre un accès stratégique au port de Douala et à ses flux de marchandises.\n\nLe bâtiment propose un grand volume ouvert, non aménagé, qui se prête au stockage, à la distribution et aux opérations logistiques. Une implantation de premier choix pour un importateur, un transitaire ou un distributeur cherchant à réduire ses délais et ses coûts de transit portuaire. Le loyer est de 7 000 000 FCFA par mois.",
    descriptionEn:
      "2,000 sqm warehouse located in the Bonanjo port zone, immediately next to Bonanjo Gate 1, the Marché des Fleurs and Bonapriso. The location offers strategic access to the port of Douala and its freight flows.\n\nThe building provides a large open, unfitted volume suited to storage, distribution and logistics operations. A prime location for an importer, a freight forwarder or a distributor seeking to cut port transit times and costs. The rent is 7,000,000 FCFA per month.",
    city: "Douala",
    neighborhood: "Zone portuaire",
    address: "Zone portuaire-Bonanjo, près de Bonanjo Gate 1, Douala",
    propertyType: "Entrepôt",
    transactionType: "location",
    price: 7000000,
    pricePeriod: "mois",
    livingArea: 2000,
    amenities: [
      "Accès stratégique au port",
      "Proche de Bonanjo Gate 1",
      "Proche du Marché des Fleurs",
      "Proche de Bonapriso",
      "Grand volume ouvert non aménagé",
      "Adapté au stockage",
      "Adapté à la distribution",
      "Adapté à la logistique",
    ],
    amenitiesEn: [
      "Strategic port access",
      "Close to Bonanjo Gate 1",
      "Close to Marché des Fleurs",
      "Close to Bonapriso",
      "Large open unfitted volume",
      "Suitable for storage",
      "Suitable for distribution",
      "Suitable for logistics",
    ],
    images: [px(24246926), px(5827062), px(4487364), px(12999283)],
    featured: false,
    source: "SE LOGER CM",
    sourceUrl:
      "https://selogercm.com/annonce/douala-zone-portuaire-bonanjo-warehouse-2000-m-zone-portuaire-bonanjo-pres-bonanjo-gate-1-17801152",
    sourceReference: "selogercm-17801152",
    seoTitle:
      "Entrepôt 2 000 m² à louer en zone portuaire Bonanjo, Douala — 7 000 000 FCFA/mois",
    seoDescription:
      "Entrepôt de 2 000 m² en zone portuaire-Bonanjo, près de Bonanjo Gate 1, Douala. Accès direct au port, idéal stockage et logistique. 7 000 000 FCFA/mois.",
  },
];
